# Generated by Django 4.2.7 on 2023-11-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderAuthor',
            new_name='OrderInfo',
        ),
        migrations.RenameIndex(
            model_name='orderinfo',
            new_name='orders_orde_created_d3a4a5_idx',
            old_name='orders_orde_created_df5f42_idx',
        ),
    ]
